import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import AuthProvider from '@/context/AuthProviders';
import { SongProvider } from '@/context/SongContextProvider';
import { Toaster } from 'react-hot-toast';
import MusicPlayer from '@/components/MusicPlayer';
import Navbar from '@/components/Navbar';
import Header from '@/components/Header';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'SwarasMusic',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full overflow-hidden">
      <AuthProvider>
        <SongProvider>
          <body
            className={`${poppins.className}  antialiased flex bg-[#0E0E0E] h-full overflow-hidden`}
          >
            <Toaster
              position="top-right"
              toastOptions={{
                style: {
                  background: '#1f1f1f',
                  color: '#fff',
                },
              }}
              reverseOrder={false}
            />
            <Navbar />
            <div className="flex-1 h-full relative overflow-hidden bg-black">
              <Header />
              <div className="h-full overflow-y-auto pr-2 pb-28 pt-20">{children}</div>
              <MusicPlayer />
            </div>
          </body>
        </SongProvider>
      </AuthProvider>
    </html>
  );
}
