import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Playpen_Sans } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProviders";
import { SongProvider } from "@/context/SongContextProvider";
import { Toaster } from "react-hot-toast";
import MusicPlayer from "@/components/MusicPlayer";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const playpen = Playpen_Sans({
  subsets: ["latin"],
  variable: "--font-playpen-Sans",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full overflow-hidden">
      <AuthProvider>
        <SongProvider>
          <body
            className={`${poppins.className}  antialiased flex bg-[#0E0E0E] h-full overflow-hidden`}
          >
            <Toaster
              position="top-right"
              toastOptions={{
                style: {
                  background: "#1f1f1f",
                  color: "#fff",
                },
              }}
              reverseOrder={false}
            />
            <Navbar />
            <div className="flex-1 h-full relative overflow-hidden bg-black">
              <div className="h-full overflow-y-auto pr-2 pb-28">
                {children}
              </div>
              <MusicPlayer />
            </div>
          </body>
        </SongProvider>
      </AuthProvider>
    </html>
  );
}
